org.gradle.jvmargs=-Xmx4608m
android.useAndroidX=true
android.enableJetifier=true
org.gradle.internal.http.connectionTimeout=60000
org.gradle.internal.http.socketTimeout=60000
android.newDsl=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
kotlin.incremental=false
