// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyObg0okwSIGdKQpHyzWHqk8xSBlwLK7w',
    appId: '1:655632443224:android:72e8266a144fec6d60e72d',
    messagingSenderId: '655632443224',
    projectId: 'ebazar-ef30c',
    storageBucket: 'ebazar-ef30c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6btHOHSWRKyoERLlpnVsdxmFHnb4YzXQ', // API Key
    appId: '1:655632443224:ios:ba9c90b698d88d5260e72d', // App ID for iOS
    messagingSenderId: '655632443224', // Messaging Sender ID (project_number)
    projectId: 'ebazar-ef30c', // Project ID
    storageBucket: 'ebazar-ef30c.firebasestorage.app', // Storage Bucket
    iosClientId:
        '655632443224-quel8ra5ns2hrsu4shnngjimseo5ejla.apps.googleusercontent.com', // iOS Client ID
    iosBundleId: 'com.ebozor.app', // iOS Bundle ID
  );
}
